module.exports.descriptors = [
    "Spiritual",
    "Sacred",
    "Royal",
    "Heritage",
    "Mystical",
    "Ancient",
    "Divine",
    "Cultural",
    "Enchanting",
    "Serene",
    "Bustling",
    "Vibrant",
    "Timeless",
    "Hidden",
    "Rustic",
    "Verdant",
    "Tranquil",
    "Harmonious",
    "Historic",
    "Lively",
  ];
  
  module.exports.places = [
    "Ghat",
    "Sanctuary",
    "Mangrove",
    "Tea Estate",
    "Backwaters",
    "Fort",
    "Dunes",
    "Stepwell",
    "Cave",
    "Reservoir",
    "Temple Town",
    "Monastery",
    "Sundarbans",
    "Delta",
    "Pass",
    "Valley",
    "Plateau",
    "Confluence",
    "Shore",
    "Forest Retreat",
  ];
  